name: AndroidBuild

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: ["Siva", "Sangar", "Production", "Stage"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: |
          if [ "${{ matrix.flavor }}" == "Production" ]; then
            ./gradlew assembleProductionDebug
          elif [ "${{ matrix.flavor }}" == "Stage" ]; then
            ./gradlew assembleStageDebug
          else
            ./gradlew assemble${{ matrix.flavor }}Debug
          fi

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: AndroidBuild-${{ matrix.flavor }}.apk
          path: app/build/outputs/apk/${{ matrix.flavor }}/debug/app-${{ matrix.flavor }}-debug.apk
